CREATE TABLE test_all_types (
    id INT PRIMARY KEY AUTO_INCREMENT,
    col_tinyint TINYINT,
    col_tinyint_unsigned TINYINT UNSIGNED,
    col_smallint SMALLINT,
    col_smallint_unsigned SMALLINT UNSIGNED,
    col_mediumint MEDIUMINT,
    col_mediumint_unsigned MEDIUMINT UNSIGNED,
    col_int INT,
    col_int_unsigned INT UNSIGNED,
    col_bigint BIGINT,
    col_bigint_unsigned BIGINT UNSIGNED,
    col_float FLOAT,
    col_double DOUBLE,
    col_decimal DECIMAL(20,6),
    col_bit BIT(8),
    col_date DATE,
    col_datetime DATETIME(3),
    col_timestamp TIMESTAMP(3),
    col_time TIME(3),
    col_year YEAR,
    col_char CHAR(10),
    col_varchar VARCHAR(255),
    col_binary BINARY(10),
    col_varbinary VARBINARY(255),
    col_tinytext TINYTEXT,
    col_text TEXT,
    col_mediumtext MEDIUMTEXT,
    col_longtext LONGTEXT,
    col_tinyblob TINYBLOB,
    col_blob BLOB,
    col_mediumblob MEDIUMBLOB,
    col_longblob LONGBLOB,
    col_enum ENUM('value1','value2','value3'),
    col_set SET('a','b','c','d'),
    col_json JSON,
    col_nullable INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO test_all_types (
    col_tinyint, col_tinyint_unsigned,
    col_smallint, col_smallint_unsigned,
    col_mediumint, col_mediumint_unsigned,
    col_int, col_int_unsigned,
    col_bigint, col_bigint_unsigned,
    col_float, col_double, col_decimal,
    col_bit,
    col_date, col_datetime, col_timestamp, col_time, col_year,
    col_char, col_varchar, col_binary, col_varbinary,
    col_tinytext, col_text, col_mediumtext, col_longtext,
    col_tinyblob, col_blob, col_mediumblob, col_longblob,
    col_enum, col_set, col_json, col_nullable
) VALUES (
    1, 255,
    100, 65535,
    1000, 16777215,
    100000, 4294967295,
    1000000, 18446744073709551615,
    1.5, 2.5, 123.456789,
    255,
    '2026-04-22', '2026-04-22 10:30:45.123', '2026-04-22 10:30:45.123', '10:30:45', 2026,
    'hello', 'world test', UNHEX('48656C6C6F'), UNHEX('576F726C64'),
    'tiny text', 'normal text', 'medium text', 'long text',
    UNHEX('AB'), UNHEX('CDEF'), UNHEX('010203'), UNHEX('FFFEFD'),
    'value1', 'a,b', '{"test": true}', 42
);
